name: Crop Productivity Maize Pipeline

# Ejecutar cada lunes a medianoche (00:00)
on:
  schedule:
    - cron: '0 0 * * 1'  # Sintaxis: 'minuto hora día_mes mes día_semana'

  push:  # Mantener la opción de ejecutarse también cuando se haga push
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools xarray cdsapi matplotlib boto3 python-dotenv numba netCDF4 scikit-learn seaborn pandas

    - name: Copy .cdsapirc to home directory
      run: cp App/.cdsapirc ~/.cdsapirc
      
    - name: Crop Productivity Maize - Extract
      working-directory: App
      run: python CropProductivityMaize_Extract.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    - name: Crop Productivity Maize - Transform and Load
      working-directory: App
      run: python CropProductivityMaize_TransformAndLoad.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    - name: SQLite - Create and Upload
      working-directory: App
      run: CreateDatabase.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
